<!DOCTYPE html>
<html>
    <body>
        <section class="homepage slider">
            <div id="myCarousel" class="owl-carousel owl-theme">
                    <!--Accepted feedback's are loaded into the carousel using AJAX-->
            </div>
        </section>
    </body>

    <script type="text/x-magento-init">
    {
        "*":{
        "scroller":{}
        }
    }
    </script>

</html>

